packages:
  - 'electron'
  - 'extensions/*'
  - 'vscode/*'

shamefullyHoist: true

overrides:
  '@vscode/ripgrep': '1.17.1'
  zod: '3.25.76'

allowBuilds:
  '@parcel/watcher': true
  '@theia/ffmpeg': true
  '@vscode/ripgrep': true
  command-join: true
  drivelist: true
  electron: true
  esbuild: true
  keytar: true
  msgpackr-extract: true
  native-keymap: true
  node-pty: true
  puppeteer: true

patchedDependencies:
  '@theia/ai-core@1.71.1': patches/@theia__ai-core@1.71.1.patch
  '@theia/core@1.71.1': patches/@theia__core@1.71.1.patch
  '@theia/monaco@1.71.1': patches/@theia__monaco@1.71.1.patch
  '@theia/navigator@1.71.1': patches/@theia__navigator@1.71.1.patch
  '@theia/notebook@1.71.1': patches/@theia__notebook@1.71.1.patch
  '@theia/plugin-ext-vscode@1.71.1': patches/@theia__plugin-ext-vscode@1.71.1.patch
  '@theia/preferences@1.71.1': patches/@theia__preferences@1.71.1.patch
  '@theia/search-in-workspace@1.71.1': patches/@theia__search-in-workspace@1.71.1.patch
  '@theia/task@1.71.1': patches/@theia__task@1.71.1.patch
  '@theia/vsx-registry@1.71.1': patches/@theia__vsx-registry@1.71.1.patch
